#!/bin/bash

# Make self-signed SSL cert and key
if [ ! -f "/home/zcluser/certs/server.key" ] || [ ! -f "/home/zcluser/certs/server.crt" ]; then
  echo "No certificates provided as a VOLUME - generating new keypair"
  mkdir /home/zcluser/certs
  openssl genrsa -des3 -passout pass:x -out server.pass.key 2048
  openssl rsa -passin pass:x -in server.pass.key -out certs/server.key
  openssl req -new -key certs/server.key -out server.csr -subj "/C=NL/CN=electrumx.zclassic.org"
  openssl x509 -req -days 1825 -in server.csr -signkey server.key -out certs/server.crt
  rm server.pass.key
  rm server.csr
  echo "Key pair generated succesfully"
else
  echo "Custom certificates provided "
fi


source /home/zcluser/default_config

echo "$RPCUSER"
echo "$RPCPASS"

[[ "$RPCUSER" ]] || RPCUSER=$DEFAULT_RPCUSER
[[ "$RPCPASS" ]] || RPCPASS=$DEFAULT_RPCPASS

# Update RPC username and password
sed -ie s/rpcuser=change-this/rpcuser=${RPCUSER}/ zclassic.conf
sed -ie s/rpcpassword=change-this/rpcpassword=${RPCPASS}/ zclassic.conf

cp zclassic.conf ~/.zclassic/

if [ ! -f "/home/zcluser/.zcash-params/sprout-proving.key" ]; then
  echo "Fetching zcash params"
  /home/zcluser/zclassic/zcutil/fetch-params.sh
fi

echo "Veryfing sha256 sums of zcash params $VK_SHA256 and $PK_SHA256"

[[ "$(sha256sum /home/zcluser/.zcash-params/sprout-verifying.key | awk '{print $1}')" != "$VK_SHA256" ]] && echo "FATAL - zcash params veryfing key checksum does not match!" && exit 1
#[[ "$(sha256sum /home/zcluser/.zcash-params/sprout-proving.key | awk '{print $1}')" != "$PK_SHA256" ]] && echo "FATAL - zcash params proving key checksum does not match!" && exit 1


/home/zcluser/zclassic/src/zcashd -daemon

COIN=Zclassic DB_DIRECTORY=/home/zcluser/zcl_electrum_db DAEMON_URL=http://${RPCUSER}:${RPCPASS}@127.0.0.1:8232 HOST=0.0.0.0 SSL_PORT=50002 PEER_DISCOVERY=Off SSL_CERTFILE=/home/zcluser/certs/server.crt SSL_KEYFILE=/home/zcluser/certs/server.key BANDWIDTH_LIMIT=10000000 /home/zcluser/electrumx/electrumx_server.py
